apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "created-component"
  title: "A repo created by a backstage template"
  description: "I clicked some buttons and this repo was created"
  annotations:
    github.com/project-slug: ceusebi-eb/backstage-test
    circleci.com/project-slug: github/eventbrite/kubernetes-devenv
spec:
  type: service
  owner: user:guests
  lifecycle: experimental  
